import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { Store, message, ago } from './core';
import { Icon } from './ui';
@Component({selector:'app-auth',imports:[FormsModule,RouterLink,Icon],template:`<div class="auth-wrap"><section class="auth-panel"><a class="brand" routerLink="/"><span class="brand-mark">T</span>Truyen<span>Dex</span></a><h1>{{register()?'Tạo tài khoản':'Chào mừng trở lại'}}</h1><p class="muted">{{register()?'Lưu những bộ truyện yêu thích và tiếp tục hành trình của bạn.':'Đăng nhập để đồng bộ truyện theo dõi và lịch sử đọc.'}}</p><form (ngSubmit)="submit()">@if(register()){<label>Tên hiển thị<input name="name" [(ngModel)]="name" required minlength="2" maxlength="60" autocomplete="nickname" placeholder="Tên của bạn"></label>}<label>Email<input type="email" name="email" [(ngModel)]="email" required maxlength="254" autocomplete="email" placeholder="ban@example.com"></label><label>Mật khẩu<input type="password" name="password" [(ngModel)]="password" required [minlength]="register()?10:1" maxlength="128" [autocomplete]="register()?'new-password':'current-password'" placeholder="Tối thiểu 10 ký tự"></label>@if(register()){<label>Nhập lại mật khẩu<input type="password" name="confirm" [(ngModel)]="confirm" required autocomplete="new-password" placeholder="Nhập lại mật khẩu"></label>}@if(error()){<p class="error" role="alert">{{error()}}</p>}<button class="primary" [disabled]="busy()">{{busy()?'Đang xử lý…':register()?'Đăng ký':'Đăng nhập'}} <app-icon name="chevron"/></button></form><p>{{register()?'Đã có tài khoản?':'Chưa có tài khoản?'}} <a [routerLink]="register()?'/dang-nhap':'/dang-ky'" [queryParams]="{returnUrl:returnUrl}">{{register()?'Đăng nhập':'Đăng ký ngay'}}</a></p><small class="muted">Tài khoản riêng của bản clone TruyenDex.</small></section></div>`})
export class Auth {
 store=inject(Store);route=inject(ActivatedRoute);router=inject(Router);register=signal(false);busy=signal(false);error=signal('');name='';email='';password='';confirm='';returnUrl='/';
 constructor(){this.route.url.subscribe(()=>{this.register.set(this.router.url.startsWith('/dang-ky'));this.error.set('');});const ret=this.route.snapshot.queryParamMap.get('returnUrl');if(ret?.startsWith('/'))this.returnUrl=ret;}
 async submit(){if(this.register()&&this.password!==this.confirm){this.error.set('Mật khẩu nhập lại chưa trùng khớp.');return;}this.busy.set(true);this.error.set('');try{await this.store.login(this.email,this.password,this.register()?this.name:undefined);this.store.notify('Đăng nhập thành công.');void this.router.navigateByUrl(this.returnUrl);}catch(e){this.error.set(message(e));}finally{this.busy.set(false);}}
}
@Component({selector:'app-library',imports:[RouterLink,Icon],template:`<div class="section-title"><h1><app-icon [name]="history()?'clock':'heart'"/> {{history()?'Lịch sử đọc truyện':'Truyện đang theo dõi'}}</h1><span class="muted">{{items().length}} truyện</span></div><p class="muted">{{store.user()?'Được đồng bộ với tài khoản của bạn.':'Lịch sử được lưu trên thiết bị này. Đăng nhập để đồng bộ giữa các thiết bị.'}}</p>@if(!history()&&!store.user()){<div class="empty-state"><app-icon name="heart"/><h2>Giữ những câu chuyện bạn yêu thích</h2><p>Đăng nhập để theo dõi truyện và quay lại đọc bất cứ lúc nào.</p><a class="primary" routerLink="/dang-nhap" [queryParams]="{returnUrl:'/theo-doi'}">Đăng nhập</a></div>}@else{<div class="library-grid">@for(item of items();track item.mangaId){<article class="library-card"><a [routerLink]="['/truyen-tranh',item.mangaId]"><img [src]="item.cover" [alt]="item.title" referrerpolicy="no-referrer"></a><div><h2><a [routerLink]="['/truyen-tranh',item.mangaId]">{{item.title}}</a></h2>@if(history()){<p>{{item.chapterTitle}}</p><small class="muted">{{ago(item.readAt!)}} trước</small><a class="primary" [routerLink]="['/chuong',item.chapterId]">Đọc tiếp <app-icon name="chevron"/></a><button class="text-button" (click)="remove(item.mangaId)">Xóa khỏi lịch sử</button>}@else{<a class="primary" [routerLink]="['/truyen-tranh',item.mangaId]">Xem truyện <app-icon name="chevron"/></a>}</div></article>}</div>@if(!items().length){<div class="empty-state"><app-icon name="book"/><h2>{{history()?'Bạn chưa đọc truyện nào':'Bạn chưa theo dõi truyện nào'}}</h2><p>Một câu chuyện mới đang chờ bạn.</p><a class="primary" routerLink="/">Khám phá truyện</a></div>}}`})
export class Library {
 store=inject(Store);router=inject(Router);route=inject(ActivatedRoute);history=signal(false);ago=ago;
 constructor(){this.route.url.subscribe(()=>this.history.set(this.router.url.includes('lich-su')));if(this.store.user())void this.store.refreshLibrary().catch(e=>this.store.notify(message(e)));}
 items(){return this.history()?this.store.history():this.store.follows();}
 async remove(id:string){try{await this.store.removeHistory(id);}catch(e){this.store.notify(message(e));}}
}
@Component({selector:'app-not-found',imports:[RouterLink,Icon],template:`<div class="empty-state"><app-icon name="book"/><h1>Không tìm thấy trang</h1><p>Đường dẫn này không tồn tại hoặc đã thay đổi.</p><a class="primary" routerLink="/">Về trang chủ</a></div>`})
export class NotFound {}
