import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { Api, Store, Manga, Chapter, Comment, Page, Reader as ReaderData, message, statuses, compact, ago, proxyImage } from './core';
import { Icon, Pagination } from './ui';
import { Sidebar } from './sidebar';
@Component({selector:'app-detail',imports:[RouterLink,FormsModule,Icon,Pagination,Sidebar],template:`
<div class="breadcrumb"><a routerLink="/nettrom">Trang chủ</a><span>›</span><span>{{manga()?.title || 'Chi tiết truyện'}}</span></div>
@if(loading()){<div class="loading-panel">Đang tải thông tin truyện…</div>}
@if(error()){<div class="error-state"><p>{{error()}}</p><button class="primary" (click)="load()">Thử lại</button></div>}
@if(manga();as m){<div class="columns"><div><section class="detail-hero"><div class="detail-cover"><img [src]="m.cover" [alt]="m.title" fetchpriority="high" decoding="async" referrerpolicy="no-referrer" (load)="$any($event.target).classList.add('loaded')" (error)="$any($event.target).classList.add('loaded')"><button class="primary" (mouseenter)="preloadFirstChapter()" (click)="readFirst()" [disabled]="reading()"><app-icon name="book"/> {{reading()?'Đang mở…':'Đọc từ đầu'}}</button><button class="secondary follow" [class.followed]="store.isFollowed(m.id)" (click)="follow()" [disabled]="following()"><app-icon [name]="store.isFollowed(m.id)?'check':'heart'"/> {{store.isFollowed(m.id)?'Đang theo dõi':'Theo dõi'}}</button>@if(resume()){<a class="resume" (mouseenter)="preloadFirstChapter()" [routerLink]="['/nettrom/chuong',resume()?.chapterId]">Đọc tiếp →</a>}</div><div class="detail-info"><h1>{{m.title}}</h1><small>Tên khác:</small><p class="alternative">{{m.alternativeTitle}}</p><div class="detail-stats"><span><app-icon name="star"/> {{m.rating.toFixed(2)}} / 10</span><span><app-icon name="heart"/> {{compact(m.follows)}}</span><span><app-icon name="comment"/> {{commentsTotal()}}</span></div><dl><dt>Tác giả</dt><dd>{{m.author || 'Đang cập nhật'}}</dd><dt>Tình trạng</dt><dd>{{statuses[m.status] || m.status}} <small class="year">{{m.year}}</small></dd><dt>Ngôn ngữ gốc</dt><dd>{{countries[m.country] || m.country}}</dd><dt>Nội dung</dt><dd>{{m.contentRating==='safe'?'An toàn':m.contentRating==='suggestive'?'16+':'18+'}}</dd><dt>Nguồn</dt><dd><a [href]="'https://mangadex.org/title/'+m.id" target="_blank" rel="noopener noreferrer">MangaDex ↗</a></dd></dl><div class="tags">@for(g of m.genres;track g){<button (click)="findGenre(g)">{{g}}</button>}</div></div></section>
<section class="panel summary"><h2><app-icon name="menu"/> Tóm tắt nội dung</h2><p class="description" [class.expanded]="expanded">{{m.description || 'Chưa có mô tả cho truyện này.'}}</p>@if(m.description.length>450){<button class="text-button" (click)="expanded=!expanded">{{expanded?'Thu gọn':'Xem thêm'}} ↓</button>}
<div class="section-title"><h2><app-icon name="book"/> Danh sách chương</h2><div class="chapter-options"><select aria-label="Ngôn ngữ chương" [(ngModel)]="language" (ngModelChange)="chapterPage.set(1);loadChapters();preloadFirstChapter()"><option value="vi">Tiếng Việt</option><option value="en">Tiếng Anh</option></select><button class="secondary" (click)="ascending=!ascending;chapterPage.set(1);loadChapters()">{{ascending?'↑ Cũ → mới':'↓ Mới → cũ'}}</button></div></div>
@if(chapterLoading()){<p class="empty-small">Đang tải danh sách chương…</p>}@else{<div class="chapter-list">@for(c of chapters();track c.id){<a [routerLink]="['/nettrom/chuong',c.id]"><span>{{c.title}}<small>{{c.group}}</small></span><time>{{ago(c.publishedAt)}}</time></a>}</div>@if(!chapters().length){<div class="empty-small">{{chapterError() || 'Không có chương ở ngôn ngữ này. Hãy thử đổi ngôn ngữ; chương có thể đã được gỡ ở nguồn.'}}@if(chapterError()){<button (click)="loadChapters()">Thử lại</button>}</div>}<app-pagination [page]="chapterPage()" [total]="chapterTotal()" [size]="100" [change]="changeChapterPage"/>}</section>
<section class="panel"><div class="section-title"><h2><app-icon name="star"/> Đánh giá của bạn</h2><small class="muted">Cộng đồng tại bản clone: {{community().rating.toFixed(1)}} · {{community().votes}} lượt</small></div><div class="rating-buttons">@for(n of scores;track n){<button [class.active]="community().myRating===n" [attr.aria-label]="'Đánh giá '+n+' điểm'" (click)="rate(n)">{{n}}</button>}</div></section>
<section class="panel"><h2><app-icon name="comment"/> Bình luận <small class="muted">({{commentsTotal()}})</small></h2>@if(store.user()){<form (ngSubmit)="postComment()"><textarea name="comment" [(ngModel)]="body" rows="3" maxlength="2000" placeholder="Chia sẻ cảm nhận của bạn về bộ truyện…" required></textarea><div class="comment-submit"><small class="muted">{{body.length}} / 2.000</small><button class="primary" [disabled]="posting()||!body.trim()">{{posting()?'Đang gửi…':'Gửi bình luận'}}</button></div></form>}@else{<p class="login-prompt"><a routerLink="/dang-nhap">Đăng nhập</a> để bình luận và cùng thảo luận.</p>}
@for(c of comments();track c.id){<div class="comment"><span class="avatar">{{c.name.slice(0,1)}}</span><div><strong>{{c.name}}</strong><small>{{ago(c.createdAt)}} trước</small><p>{{c.body}}</p>@if(store.user()?.id===c.userId||store.user()?.role==='admin'){<button class="text-button" (click)="deleteComment(c.id)">Xóa bình luận</button>}</div></div>}@if(!comments().length){<p class="empty-small muted">Chưa có bình luận nào.</p>}@if(commentsTotal()>20){<app-pagination [page]="commentPage()" [total]="commentsTotal()" [size]="20" [change]="changeCommentPage"/>}</section>
</div><app-sidebar/></div>}`})
export class Detail {
 api=inject(Api);store=inject(Store);route=inject(ActivatedRoute);router=inject(Router);manga=signal<Manga|null>(null);loading=signal(true);error=signal('');chapters=signal<Chapter[]>([]);chapterPage=signal(1);chapterTotal=signal(0);chapterLoading=signal(false);chapterError=signal('');firstChapter=signal<Chapter|null>(null);comments=signal<Comment[]>([]);commentsTotal=signal(0);commentPage=signal(1);community=signal({rating:0,votes:0,myRating:0});posting=signal(false);following=signal(false);reading=signal(false);preloaded=false;language=this.store.settings().language;ascending=false;expanded=false;body='';id='';epoch=0;chapterEpoch=0;scores=[1,2,3,4,5,6,7,8,9,10];statuses=statuses;compact=compact;ago=ago;countries:Record<string,string>={ja:'Nhật Bản',ko:'Hàn Quốc',zh:'Trung Quốc',en:'Tiếng Anh'};
 constructor(){this.route.paramMap.subscribe(p=>{this.id=p.get('id')!;this.chapterPage.set(1);this.commentPage.set(1);this.manga.set(null);this.firstChapter.set(null);this.preloaded=false;void this.load();});}
 async load(){const n=++this.epoch;this.loading.set(true);this.error.set('');this.firstChapter.set(null);try{const m=await this.api.request<Manga>('/catalog/'+this.id,'GET',undefined,true);if(n!==this.epoch)return;this.manga.set(m);void this.loadChapters();void this.loadComments();void this.loadCommunity();setTimeout(()=>void this.preloadFirstChapter(),3000);}catch(e){if(n===this.epoch)this.error.set(message(e));}finally{if(n===this.epoch)this.loading.set(false);}}
 async preloadFirstChapter(){if(this.preloaded)return;try{const r=await this.api.request<Page<Chapter>>(`/catalog/${this.id}/chapters?language=${this.language}&ascending=true&page=1`,'GET',undefined,true);const first=r.items[0];if(!first)return;this.firstChapter.set(first);this.preloaded=true;const chapterData=await this.api.request<ReaderData>(`/chapters/${first.id}`);if(!chapterData)return;const pages=(this.store.settings().dataSaver&&chapterData.dataSaverPages?.length?chapterData.dataSaverPages:chapterData.pages)||[];pages.slice(0,5).forEach(url=>{const img=new Image();img.src=proxyImage(url);});}catch{}}
 async loadChapters(){const n=++this.chapterEpoch;this.chapterLoading.set(true);this.chapterError.set('');try{const r=await this.api.request<Page<Chapter>>(`/catalog/${this.id}/chapters?`+this.api.query({page:this.chapterPage(),language:this.language,ascending:this.ascending}),'GET',undefined,true);if(n===this.chapterEpoch){this.chapters.set(r.items);this.chapterTotal.set(r.total);}}catch(e){this.chapters.set([]);this.chapterError.set(message(e));}finally{if(n===this.chapterEpoch)this.chapterLoading.set(false);}}
 changeChapterPage=(p:number)=>{this.chapterPage.set(p);void this.loadChapters();};
 changeCommentPage=(p:number)=>{this.commentPage.set(p);void this.loadComments();};
 async loadComments(){try{const r=await this.api.request<Page<Comment>>(`/comments?mangaId=${this.id}&page=${this.commentPage()}`);this.comments.set(r.items);this.commentsTotal.set(r.total);}catch(e){this.store.notify(message(e));}}
 async loadCommunity(){try{this.community.set(await this.api.request(`/catalog/${this.id}/community`));}catch{}}
 resume(){return this.store.history().find(x=>x.mangaId===this.id);}
 async follow(){if(!this.store.user()){void this.router.navigate(['/dang-nhap'],{queryParams:{returnUrl:this.router.url}});return;}this.following.set(true);try{await this.store.follow(this.manga()!);}catch(e){this.store.notify(message(e));}finally{this.following.set(false);}}
 async readFirst(){const first=this.firstChapter();if(first){void this.router.navigate(['/nettrom/chuong',first.id]);return;}this.reading.set(true);try{const r=await this.api.request<Page<Chapter>>(`/catalog/${this.id}/chapters?language=${this.language}&ascending=true&page=1`,'GET',undefined,true);if(r.items[0]){this.firstChapter.set(r.items[0]);void this.router.navigate(['/nettrom/chuong',r.items[0].id]);}else this.store.notify('Chưa có chương ở ngôn ngữ này. Hãy thử đổi ngôn ngữ.');}catch(e){this.store.notify(message(e));}finally{this.reading.set(false);}}
 async findGenre(name:string){try{const tags=await this.api.request<{id:string;name:string}[]>('/catalog/tags');const t=tags.find(x=>x.name===name);if(t)void this.router.navigate(['/nettrom/tim-truyen-nang-cao'],{queryParams:{genre:t.id}});}catch(e){this.store.notify(message(e));}}
 async rate(score:number){if(!this.store.user()){this.store.notify('Vui lòng đăng nhập để đánh giá.');return;}try{await this.api.request(`/catalog/${this.id}/rating`,'PUT',{score});await this.loadCommunity();this.store.notify('Đã lưu đánh giá của bạn.');}catch(e){this.store.notify(message(e));}}
 async postComment(){this.posting.set(true);try{await this.api.request(`/catalog/${this.id}/comments`,'POST',{body:this.body});this.body='';this.commentPage.set(1);await this.loadComments();this.store.notify('Đã gửi bình luận.');}catch(e){this.store.notify(message(e));}finally{this.posting.set(false);}}
 async deleteComment(id:string){try{await this.api.request('/comments/'+id,'DELETE');await this.loadComments();}catch(e){this.store.notify(message(e));}}
}
