import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { Api, Store, Manga, Page, message } from './core';
import { Icon, MangaCardComponent, Pagination } from './ui';
@Component({selector:'app-search',imports:[FormsModule,Icon,MangaCardComponent,Pagination],template:`
<div class="section-title"><h1><app-icon name="search"/> Tìm truyện nâng cao</h1><span class="muted">Tìm câu chuyện dành cho bạn</span></div>
<form class="filter-panel" (ngSubmit)="submit()"><div class="filter-title"><label>Tựa đề<input type="search" name="q" [(ngModel)]="form.q" placeholder="Nhập tên truyện bạn muốn tìm…"></label><button class="secondary" type="button" (click)="expanded=!expanded"><app-icon name="filter"/> {{expanded?'Thu gọn bộ lọc':'Hiển thị bộ lọc'}}</button></div>
@if(expanded){<div class="filter-grid"><label>Thể loại<select name="genre" [(ngModel)]="form.genre"><option value="">Tất cả thể loại</option>@for(t of tags();track t.id){<option [value]="t.id">{{t.name}}</option>}</select></label><label>Tình trạng<select name="status" [(ngModel)]="form.status"><option value="">Tất cả tình trạng</option><option value="ongoing">Đang tiến hành</option><option value="completed">Đã hoàn thành</option><option value="hiatus">Tạm ngưng</option><option value="cancelled">Đã hủy</option></select></label><label>Quốc gia<select name="country" [(ngModel)]="form.country"><option value="">Tất cả quốc gia</option><option value="ja">Nhật Bản</option><option value="ko">Hàn Quốc</option><option value="zh">Trung Quốc</option><option value="en">Tiếng Anh</option></select></label><label>Đối tượng<select name="demographic" [(ngModel)]="form.demographic"><option value="">Tất cả</option><option value="shounen">Shounen · Thiếu niên</option><option value="shoujo">Shoujo · Thiếu nữ</option><option value="seinen">Seinen</option><option value="josei">Josei</option></select></label><label>Ngôn ngữ bản dịch<select name="language" [(ngModel)]="form.language"><option value="vi">Tiếng Việt</option><option value="en">Tiếng Anh</option></select></label><label>Năm phát hành<input type="number" min="1900" max="2100" name="year" [(ngModel)]="form.year" placeholder="Tất cả năm"></label></div>}
<div class="filter-bottom"><label>Xếp theo<select name="sort" [(ngModel)]="form.sort"><option value="latest">Mới cập nhật</option><option value="new">Truyện mới</option><option value="hot">Theo dõi nhiều nhất</option><option value="rating">Đánh giá cao nhất</option><option value="title">Bảng chữ cái</option></select></label><div><button type="button" class="secondary" (click)="reset()">Đặt lại</button><button class="primary" type="submit"><app-icon name="search"/> Tìm kiếm</button></div></div></form>
<div class="section-title"><h2>Kết quả tìm kiếm</h2><span class="muted">{{total().toLocaleString('vi')}} truyện</span></div>
@if(error()){<div class="error-state"><p>{{error()}}</p><button (click)="load()" class="primary">Thử lại</button></div>}
@if(loading()){<div class="loading-panel">Đang tìm truyện…</div>}@else{<div class="search-grid">@for(m of items();track m.id){<app-card [manga]="m"/>}</div>@if(!items().length&&!error()){<div class="empty-state"><app-icon name="search"/><h2>Không tìm thấy truyện</h2><p>Thử tên ngắn hơn hoặc bỏ bớt bộ lọc.</p><button class="primary" (click)="reset()">Xóa bộ lọc</button></div>}<app-pagination [page]="page()" [total]="total()" [size]="24" [change]="goPage"/>}`})
export class Search {
 api=inject(Api);store=inject(Store);router=inject(Router);route=inject(ActivatedRoute);tags=signal<{id:string;name:string}[]>([]);items=signal<Manga[]>([]);total=signal(0);page=signal(1);loading=signal(true);error=signal('');expanded=true;epoch=0;
 defaults=()=>({q:'',genre:'',status:'',country:'',demographic:'',language:this.store.settings().language,year:'',sort:'latest'});form=this.defaults();
 constructor(){void this.api.request<{id:string;name:string}[]>('/catalog/tags').then(r=>this.tags.set(r)).catch(()=>{});this.route.queryParamMap.subscribe(p=>{this.form=this.defaults();for(const key of Object.keys(this.form) as (keyof typeof this.form)[]){if(p.has(key))this.form[key]=p.get(key)!;}this.page.set(Math.max(1,Number(p.get('page'))||1));void this.load();});}
 submit(){void this.router.navigate(['/nettrom/tim-truyen-nang-cao'],{queryParams:{...this.form,page:1}});}
 reset(){this.form=this.defaults();this.submit();}
 goPage=(page:number)=>{void this.router.navigate([],{relativeTo:this.route,queryParams:{...this.form,page}});window.scrollTo({top:0,behavior:'smooth'});};
 async load(){const n=++this.epoch;this.loading.set(true);this.error.set('');try{const r=await this.api.request<Page<Manga>>('/catalog/search?'+this.api.query({...this.form,page:this.page(),pageSize:24}));if(n===this.epoch){this.items.set(r.items);this.total.set(r.total);}}catch(e){if(n===this.epoch)this.error.set(message(e));}finally{if(n===this.epoch)this.loading.set(false);}}
}
